# Generated by Django 4.1.1 on 2022-09-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_review',
        ),
    ]
