# Generated by Django 4.1.1 on 2022-09-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_comments_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='review',
        ),
    ]
