# Generated by Django 4.1.1 on 2022-09-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comments_children_comments_parentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='children',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parentId',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
