# Generated by Django 4.1.1 on 2022-10-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_booksadded_book_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booksadded',
            unique_together=set(),
        ),
    ]
